image: Ubuntu

stack: python 3.8

services:
  - mysql

install:
  - pip install pipenv
  - pipenv sync

test_script:
  - sh: py.test --capture=tee-sys --junit-xml=test-result.xml -c .appveyor/pytest.ini

on_finish:
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name 'test*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

build: off
