#
# Copyright (c) Ionplus AG and contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for details.
#

create table material (
    name varchar(20) primary key,
    sort_order int not null
) engine=innodb;

insert into material
values ('undefined', 0),
       ('resin', 11),
       ('wood', 12),
       ('plastics', 20),
       ('precursor', 25),
       ('biofuel', 30),
       ('biomarkers', 40),
       ('bone', 44),
       ('bulk sediment', 48),
       ('carbonate', 50),
       ('cellulose', 60),
       ('charcoal', 64),
       ('chironomids', 70),
       ('CO2', 80),
       ('co2atm', 90),
       ('coal', 100),
       ('collagen', 110),
       ('compound', 120),
       ('coprolite', 130),
       ('coral', 140),
       ('cremated bone', 150),
       ('diatom', 160),
       ('eggshell', 170),
       ('feather', 180),
       ('fiber', 190),
       ('food', 200),
       ('foraminifera', 210),
       ('fossil modern', 220),
       ('barley mash', 230),
       ('gas', 230),
       ('graphite', 240),
       ('groundwater', 250),
       ('gyttja', 251),
       ('hair', 260),
       ('hexenol', 270),
       ('horn', 280),
       ('humic acid', 290),
       ('iron', 300),
       ('ivory', 310),
       ('leather', 320),
       ('lignin', 330),
       ('liquid', 340),
       ('macrofossils', 350),
       ('methane', 360),
       ('mortar', 370),
       ('oil', 380),
       ('organic matter', 390),
       ('oxalic acid', 400),
       ('paint', 410),
       ('paper', 420),
       ('papyrus', 430),
       ('parchment', 440),
       ('pearl freshwater', 450),
       ('pearl marine', 460),
       ('peat', 470),
       ('Phthalic Acid', 480),
       ('Phthalic anhydride', 490),
       ('Phthalimide', 494),
       ('POC', 500),
       ('pollen', 510),
       ('polyethylene', 515),
       ('pottery', 520),
       ('reference', 530),
       ('roots', 550),
       ('seawater', 560),
       ('sediment', 564),
       ('seed', 570),
       ('shell marine', 580),
       ('shell terrestrial', 590),
       ('soil', 600),
       ('solid', 610),
       ('speleothem', 615),
       ('speleothom', 620),
       ('SPM', 625),
       ('SRF', 630),
       ('sucrose', 640),
       ('textile', 650),
       ('tissue', 660),
       ('toluene', 670),
       ('tooth', 680),
       ('undefined fiber', 690),
       ('water', 700),
       ('wax', 709),
       ('wine', 710),
       ('aerosol', 720);
